{{- if not (include "timothy.certAuthIsExternal" .) -}}
{{- $certAuth := .Values.web.configuration.certAuth -}}
{{- $creationDate := $certAuth.creationDate | default (now | date "2006-01-02T15:04:05 -0700" ) }}
{{- $pubKey := $certAuth.publicKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "timothy.certAuthSecretName" . }}
type: Opaque
data:
  public-key: {{ $pubKey | required "certAuth.publicKey is required"  }}
  creation-date: {{ $creationDate | b64enc }}
{{- end }}
