{{- if include "timothy.createWebRbac" . }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "timothy.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "timothy.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "timothy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
