{{- if not .Values.web.configuration.database.secretName }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "timothy.fullname" . }}-database
  labels:
    {{- include "timothy.labels" . | nindent 4 }}
data:
  {{- with .Values.web.configuration.database }}
  TIM_DB_USERNAME: {{ b64enc .username | quote }}
  TIM_DB_PASSWORD: {{ b64enc .password | quote }}
  {{- end }}
{{- end }}
