{{- $ingress := .Values.networking.ingress -}}
{{- if $ingress.enabled -}}
{{- $gitVersion := $.Capabilities.KubeVersion.GitVersion }}
{{- $httpsEnabled := include "timothy.httpsEnabled" . -}}
{{- $httpEnabled := include "timothy.httpEnabled" . -}}
{{- $fullName := include "timothy.fullname" . -}}
{{- if and $ingress.className (not (semverCompare ">=1.18-0" $gitVersion)) }}
  {{- if not (hasKey $ingress.annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set $ingress.annotations "kubernetes.io/ingress.class" $ingress.className}}
  {{- end }}
{{- end }}
apiVersion: {{ include "tonic.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "timothy.labels" . | nindent 4 }}
  annotations:
        {{- $annotations := merge .Values.global.annotations $ingress.annotations }}
        {{- if $annotations }}
        {{- toYaml $annotations | nindent 8 }}
        {{- end }}
spec:
  {{- if and $ingress.className (semverCompare ">=1.18-0" $gitVersion) }}
  ingressClassName: {{ $ingress.className }}
  {{- end }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- $portName := "http" }}
    {{- if $ingress.portName }}
    {{- $portName = $ingress.portName }}
    {{- else if not $httpEnabled }}
    {{- $portName = "https" }}
    {{- end }}
    {{- range $ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
            - path: {{ .path }}
              {{- if and .pathType (semverCompare ">=1.18-0" $gitVersion) }}
              pathType: {{ .pathType }}
              {{- end }}
              backend:
                {{- if semverCompare ">=1.19-0" $gitVersion }}
                service:
                  name: {{ $fullName }}
                  port:
                    name: {{ $portName }}
                {{- else }}
                serviceName: {{ $fullName }}
                servicePort: {{ $portName }}
                {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
