{{- $ingress := .Values.networking.ingress -}}
{{- if $ingress.enabled -}}
{{- $httpsEnabled := include "timothy.httpsEnabled" . -}}
{{- $httpEnabled := include "timothy.httpEnabled" . -}}
{{- $fullName := include "timothy.fullname" . -}}
{{- $portName := $ingress.portName }}
{{- if not $portName -}}
{{- if $httpsEnabled -}}
{{- $portName = "https" -}}
{{- else -}}
{{- $portName = "http" -}}
{{- end -}}
{{- end -}}
apiVersion: {{ include "tonic.ingressApiVersion" . }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "timothy.labels" . | nindent 4 }}
  annotations:
        {{- $annotations := merge .Values.global.annotations $ingress.annotations }}
        {{- if $annotations }}
        {{- toYaml $annotations | nindent 8 }}
        {{- end }}
spec:
  ingressClassName: {{ $ingress.className }}
  {{- if $ingress.tls }}
  tls:
    {{- range $ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range $ingress.hosts }}
    - http:
        paths:
          {{- include "timothy.ingressPaths" (dict "paths" .paths "port" $portName "service" $fullName) | nindent 10 -}}
    {{- if .host }}
      host: {{ .host | quote }}
    {{- end }}
    {{- end }}
{{- end }}
