{{- if (.Values).networking }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "timothy.fullname" . }}-nginx-config
  labels:
    {{- include "timothy.labels" . | nindent 4 }}
data:
  default.conf: |-
    {{- with .Values.networking }}
    server {
      {{- if (.http).enabled }}
      listen {{ .http.port }};
      {{- end }}
      {{- if (.https).enabled }}
      listen {{ .https.port }} ssl;
      ssl_certificate /etc/tim/certs/tls.crt;
      ssl_certificate_key /etc/tim/certs/tls.key;
      {{- end }}

      root /etc/tim/frontend/;
      index index.html;
      error_page 404  /404.html;

      location ^~ /api/ {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
      }

      location ^~ /swagger/ {
        proxy_pass http://localhost:5000;
        proxy_set_header Host $host;
      }

      # Any route containing a file extension (e.g. /devicesfile.js)
      location ~ ^.+\..+$ {
        try_files $uri =404;
      }

      location / {
        try_files $uri /index.html;
      }
    }
    {{- end }}
{{- end }}
