apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tonic-tim-server-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api$1$2
spec:
  rules:
  # Non-default SSL cert requires an FQDN.
  # - host: localhost
  #   http:
  #     paths:
  #       - path: /
  #         pathType: Prefix
  #         backend:
  #           service:
  #             name: tonic-tim-server
  #             port:
  #               number: 443
  - http: #default
      paths:
        - path: /tim/api(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: tonic-tim-server
              port:
                number: 80
